### ISSUE TITLE
Create Flu Shot Finder app for Anchorage based on Chicago app

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/project-ideas#1]
Implement Flu Shots for Anchorage http://chicagoflushots.org/

**Comment by thermokarst** [comment]
The source repository: https://github.com/tkompare/flushots2013

**Comment by thermokarst** [comment]
This project was kicked-off at the 2014 Fall Hackathon. It can be found here: https://github.com/codeforanchorage/flushots
