### ISSUE TITLE
24 Pull Requests Contributions/Participation (http://24pullrequests.com)

### ISSUE THREAD

**Issue by thermokarst** [codeforanchorage/project-ideas#11]
**One sentence description:**
24 Pull Requests is a holiday event to foster open source development (read: paced, month-long hackathon), that could see CfA involvement as contributors and/or project sponsors.

**Link (more details/brain dump/alpha):**
http://24pullrequests.com

**Project Needs (dev/design/resources):**
Seems like we could do a mix-or-match on this: maybe for some of our outstanding projects we could write up detailed feature requests that could be used as guidelines for potential contributors (or internally). Also, we could identify projects (either within CfA, the organization at-large, or general interest projects on 24pullrequests.com that have expressed a need), and split up contributions between us.

I know this is all a little late --- I only just learned of this event today (12/1).

**Status (in progress, pie-in-the-sky):**
Soliciting feedback from CfA.

**Comment by brendanbabb** [comment]
Matt, thanks for posting. This seems similar to a requirement we need to accomplish before 2015 of getting the civic tech issue finder set up for Code for Anchorage. An API that will display what we are working on and show other people easily stuff they could help with. http://www.codeforamerica.org/geeks/civicissues
